name: File Changes

on:
  workflow_dispatch:

jobs:
  job1:  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: s1
      run: |
        cd ./scripts
        ls
  
    - name: s2
      run: |
        cd ./app
        ls
        
    - name: s2
      run: |
        cd ./cypress
        cd ./e2e
        ls
