name: Run on BrowserStack

on: 
  workflow_dispatch:
    inputs:
      build-name: 
        description: 'Name of the buid'     
        required: true
        default: 'daily'

jobs:
  browser-stack:
    runs-on: ubuntu-latest

    environment: sandbox

    steps:

    - name: Info    
      run: |
        echo "Build name: ${{ github.event.inputs.build-name }}"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: 'BrowserStack Env Setup'
      uses: 'browserstack/github-actions/setup-env@master'          
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        build-name: ${{ github.event.inputs.build-name }}

    - name: BrowserStack CLI Install
      run: npm install browserstack-cypress-cli -g

    - name: Npm Install
      run: npm install

    - name: Run Tests
      run: browserstack-cypress run