name: Check Versions

on:  
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  check-versions:
    runs-on: ubuntu-latest    
    # container:
    #   image: docker/github-actions

    steps:
      - name: sls install
        run: npm install -g serverless

      - name: sls version
        run: serverless --version

      - name: docker version
        run: docker --version

      - name: aws version
        run: aws --version
