name: File Changes

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
      
  workflow_dispatch:
    inputs:
      test-suite:
        type: choice
        description: 'Run Test Suite'
        default: "-all-"
        options:
          - "-all-"
          - "Query Helper"
          - "APIHandler"
          - "ListingManager"
          - "EntityHelper"
          - "PaymentService"
          - "ExternalOrdersHandler"
          - "ticketsHooks"
          - "WebhooksHandler"
          - "AvailableBalanceHandler"
          - "BalanceManager"
          - "UUID"
          - "listingUtil"
          - "dateUtil"
      test-suite2:
        type: choice
        description: 'Run Test Suite'
        default: "-all-"
        options:
          - "-all-"
          - "Query Helper"
          - "APIHandler"
          - "ListingManager"
          - "EntityHelper"
          - "PaymentService"
          - "ExternalOrdersHandler"
          - "ticketsHooks"
          - "WebhooksHandler"
          - "AvailableBalanceHandler"
          - "BalanceManager"
          - "UUID"
          - "listingUtil"
          - "dateUtil"
  
jobs:
  job1:
    if: startsWith(github.head_ref, 'chore/') == false && startsWith(github.head_ref, 'docs/') == false
    runs-on: ubuntu-latest
    
    env:
      run-on-demand: ${{ github.event_name == 'workflow_dispatch' }}
      test-suite:    ${{ github.event.inputs.test-suite || '-all-' }}
      test-suite2:    ${{ github.event.inputs.test-suite2 || '-all-' }}

    steps:
    - uses: actions/checkout@v3

    - name: run-on-demand
      if: env.run-on-demand
      run: |
        echo "run-on-demand" ${{env.test-suite}} ${{env.test-suite2}}
        
    - name: NOT-run-on-demand
      if:  env.run-on-demand == false || (env.test-suite == 'UUID' && env.test-suite2 != '-all-')
      run: |
        echo ${{env.test-suite}} ${{env.test-suite2}}
