name: File Changes

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
  
  
jobs:
  detect-important-changes:
    if: startsWith(github.head_ref, 'chore/') == false && startsWith(github.head_ref, 'docs/') == false
    
    runs-on: ubuntu-latest

    outputs:
      app-changes: ${{ steps.changes.outputs.app-changes }} 

    steps:
    - uses: actions/checkout@v3
        
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          app-changes:
            - 'app/**'

        
    - name: output
      run: |
        echo "app-changes: " ${{steps.changes.outputs.app-changes}}
      
  run-what-needed:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: output
      run: |
        echo "app-changes: " ${{needs.detect-important-changes.outputs.app-changes}}
      