name: File Changes

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
  
  
jobs:
  importan-changes-gatekeeper:
    if: startsWith(github.head_ref, 'chore/') == false && startsWith(github.head_ref, 'docs/') == false

    runs-on: ubuntu-latest

    outputs:
      app-changes: ${{ steps.changes.outputs.app-changes }} 
      
    env:      
      node_version: "--version"

    steps:
    - run: |
       node ${{ env.node_version }}
   
