name: File Changes

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check1.outputs.docs_changed }}

    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
        
    - name: check1
      run: echo ${{steps.check1.outputs.docs_changed}}

    - name: check1
      shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        $diff = git diff --name-only HEAD^ HEAD

        $filter = "^app/",".yml$" -join '|'
        
        $SourceDiff = $diff | Where {$_ -match $filter}
        $HasDiff = $SourceDiff.Length -gt 0

        echo $SourceDiff.Length
        echo $HasDiff
        echo $diff.Length
        echo $diff

        echo "docs_changed={$HasDiff}" >> $GITHUB_OUTPUT
        
    - name: check1
      run: |
        echo "docs_changed: ${{steps.check1.outputs.docs_changed}}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "docs_changed: ${{needs.job1.outputs.docs_changed}}"
