name: File Changes

on:
  push:
  workflow_dispatch:
  
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check1.outputs.docs_changed }}

    steps:
    - id: check1
      run: echo "docs_changed=True" >> $GITHUB_OUTPUT
        

    - name: check2
      run: |
        echo "docs_changed: " ${{steps.check1.outputs.docs_changed}}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "docs_changed: " ${{needs.job1.outputs.docs_changed}}
          
      - name: cond
        if: needs.job1.outputs.docs_changed == 'True'
        run: |
          echo "YES docs_changed: " ${{needs.job1.outputs.docs_changed}}
