name: File Changes

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
      
  workflow_dispatch:
  
jobs:
  job1:
    if: startsWith(github.head_ref, 'chore/') == false && startsWith(github.head_ref, 'docs/') == false
    runs-on: ubuntu-latest
    
    env:
      run-on-demand: ${{ github.event_name == 'workflow_dispatch' }}

    steps:
    - uses: actions/checkout@v3

    - name: run-on-demand
      if: run-on-demand
      run: |
        echo "run-on-demand Event: " ${{ github.event_name }}
        
    - name: NOT-run-on-demand
      if: run-on-demand == false
      run: |
        echo "NOT run-on-demand Event: " ${{ github.event_name }}
