name: File Changes

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
      
  workflow_dispatch:
  
jobs:
  job1:
    if: startsWith(github.head_ref, 'chore/') == false && startsWith(github.head_ref, 'docs/') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          app-changes:
            - 'app/**'
          cypress-changes:
            - 'cypress/**'
          json-or-yml-changes:
            - '**.json'
            - '**.yml'

        
    - name: check2
      run: |
        echo "Event: " ${{ github.event }}
        echo "app-changes: " ${{steps.changes.outputs.app-changes}}
        echo "cypress-changes: " ${{steps.changes.outputs.cypress-changes}}
        echo "json-or-yml-changes: " ${{steps.changes.outputs.json-or-yml-changes}}
