name: File Changes

on:
  pull_request:
    branches-ignore:
      - 'chore/**'
      - 'docs/**'
  
  
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          app-changes:
            - 'app/**'
          cypress-changes:
            - 'cypress/**'
          json-or-yml-changes:
            - '.json^'
            - '.yml^'

        
    - name: check2
      run: |
        echo "app-changes: " ${{steps.changes.outputs.app-changes}}
        echo "cypress-changes: " ${{steps.changes.outputs.cypress-changes}}
        echo "json-or-yml-changes: " ${{steps.changes.outputs.json-or-yml-changes}}
