name: File Changes

on:
  push:
  workflow_dispatch:
  
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check1.outputs.docs_changed }}
      docs_changed1: ${{ steps.check1.outputs.docs_changed1 }}
      docs_changed2: ${{ steps.check1.outputs.docs_changed2 }}
      docs_changed3: ${{ steps.check1.outputs.docs_changed3 }}
      docs_changed4: ${{ steps.check1.outputs.docs_changed4 }}

    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
        
    - name: check1-step
      shell: pwsh
      id: check1
      run: |
        $diff = git diff --name-only HEAD^ HEAD

        $filter = "^app/",".yml$" -join '|'
        
        $SourceDiff = $diff | Where {$_ -match $filter}
        $HasDiff = $SourceDiff.Length -gt 0

        echo $SourceDiff.Length
        echo $HasDiff
        echo $diff.Length
        echo $diff

        echo " - 1."
        echo docs_changed={$HasDiff} >> $GITHUB_OUTPUT
        echo " - 2."
        echo "docs_changed1={$HasDiff}" >> $GITHUB_OUTPUT
        echo " - 3."
        echo "{docs_changed2}={$HasDiff}" >> $GITHUB_OUTPUT      
        echo " - 4."
        echo "docs_changed3={$HasDiff}" >> $env:GITHUB_OUTPUT

        
    - name: check2
      run: |
        echo "docs_changed: " ${{steps.check1.outputs.docs_changed}}
        echo "docs_changed1: " ${{steps.check1.outputs.docs_changed1}}
        echo "docs_changed2: " ${{steps.check1.outputs.docs_changed2}}        
        echo "docs_changed3: " ${{steps.check1.outputs.docs_changed3}}
        echo "docs_changed4: " ${{steps.check1.outputs.docs_changed4}}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "docs_changed: " ${{needs.job1.outputs.docs_changed}}
          
      - name: cond
        if: needs.job1.outputs.docs_changed == 'True'
        run: |
          echo "YES docs_changed: " ${{needs.job1.outputs.docs_changed}}
