name: File Changes

on:
  push:
  workflow_dispatch:

jobs:
  conditional_step:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        $diff = git diff --name-only HEAD^ HEAD

        $filter = "^app/",".yml$" -join '|'
        
        $SourceDiff = $diff | Where {$_ -match $filter}
        $HasDiff = $SourceDiff.Length -gt 0

        echo $SourceDiff.Length
        echo $HasDiff
        echo $diff.Length
        echo $diff

        echo "{docs_changed}={$HasDiff}" >> $GITHUB_OUTPUT

    # Run the step only with "docs_changed" equals "True"
    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.docs_changed == 'True'
      run: echo publish docs
