name: File Changes

on:
  push:
  workflow_dispatch:
  
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check1.outputs.docs_changed }}

    steps:
    - name: check1
      id: check_file_changed
      run: |
        echo $diff = git diff --name-only HEAD^ HEAD
        
        echo $filter = "^app/",".yml$" -join '|'   
        
        echo $SourceDiff = $diff | Where {$_ -match $filter}
        echo $HasDiff = $SourceDiff.Length -gt 0

        echo $SourceDiff.Length
        echo $HasDiff
        echo $diff.Length
        echo $diff

        echo "docs_changed={$HasDiff}" >> $GITHUB_OUTPUT
        
    - name: check2
      run: |
        echo "docs_changed: " ${{steps.check1.outputs.docs_changed}}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "docs_changed: " ${{needs.job1.outputs.docs_changed}}
          
      - name: cond
        if: needs.job1.outputs.docs_changed == 'True'
        run: |
          echo "YES docs_changed: " ${{needs.job1.outputs.docs_changed}}
