name: File Changes

on:
  pull_request:
    branches-ignore:
      - 'chore/**'
      - 'docs/**'
  
  
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          app-changes:
            - 'app/**'

        
    - name: check2
      run: |
        echo "app-changes: " ${{steps.changes.outputs.app-changes}}
