name: Run on BrowserStack

on: 
  workflow_dispatch:
    inputs:
      build-name: 'Name of the buid'     
        required: true
        default: 'daily'

jobs:
  browser-stack:
    runs-on: ubuntu-latest

    steps:
    - name: Info
      run: |
        echo "User name: ${{ secrets.BROWSERSTACK_USERNAME }}"
        echo "Build name: ${{ github.event.inputs.build-name }}"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: 'BrowserStack Env Setup'
      uses: 'browserstack/github-actions/setup-env@master'
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        build-name: ${{ github.event.inputs.build-name }}


    - name: BrowserStack CLI Install
      run: npm install browserstack-cypress-cli

    - name: Npm Install
      run: npm install

    - name: Start local server
      run: npm run start

    - name: Run Test
      run: browserstack-cypress run