name: Sandbox

on: 
  workflow_dispatch:
on: 
  push:
    branches: ['*']

jobs:
  sandbox:
    runs-on: ubuntu-latest    
    container:
      image: docker/github-actions

    steps:
      - name: sls version
        run: serverless --version

      - name: docker version
        run: docker --version

      - name: aws version
        run: aws --version
