name: Run tests and test builds

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - 'next'
      - 'main'

jobs:
  give-info:
    if: startsWith(github.head_ref, 'chore/') == false
      && startsWith(github.head_ref, 'docs/') == false
      && github.event.pull_request.draft == false
      && startsWith(github.event.pull_request.title, 'draft:') == false
      && startsWith(github.event.pull_request.title, '[wip]') == false
   
    runs-on: ubuntu-latest
   
    steps:
      - name: Info
        run: |
          echo "Head ref: " ${{ github.head_ref }}
          echo "Ref type and name: " ${{ github.ref_type github.ref_name}}
          echo "Event: " ${{ github.event_name }}
          echo "pull_request.title: " ${{ github.event.pull_request.title }}
          echo "pull_request.draft: " ${{ github.event.pull_request.draft }}

