name: Run tests and test builds

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]
    branches:
      - 'next'
      - 'main'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        default: "sandbox"
        options:
          - "sandbox"
          - "production"

jobs:
  give-info:  
      
    runs-on: ubuntu-latest
    
    environment: ${{github.event.inputs.environment || 'sandbox' }}
   
    steps:

      - name: Info
        run: |
          echo "env.CI_SOME_KEY:" ${{ env.CI_SOME_KEY }}
          echo "Event:" ${{ github.event_name }}
          echo "pull_request.title:" ${{ github.event.pull_request.title }}
          echo "pull_request.draft:" ${{ github.event.pull_request.draft }}
          
