name: Run tests and test builds

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]
    branches:
      - 'next'
      - 'main'
  workflow_dispatch:
    inputs:
      spec-file:
        type: choice
        description: 'Run only test'
        default: "-all-"
        options:
          - "-all-"
          - "login"
          - "quickSearch"
          - "profile"
          - "event"
          - "buy_tests/ticket_buy_bank"

jobs:
  give-info:  
      
    runs-on: ubuntu-latest
    
    env:
      spec-file: ${{ github.event.inputs.spec-file || '-all-' }}
      
      
   
    steps:

      - name: Info
        run: |
          echo "env.spec-file: " ${{ env.spec-file }}
          echo "Event: " ${{ github.event_name }}
          echo "pull_request.title: " ${{ github.event.pull_request.title }}
          echo "pull_request.draft: " ${{ github.event.pull_request.draft }}
          
      - name: Run spec
        if: env.spec-file != '-all-'
        run: |
          echo "Will run only: " ${{ env.spec-file }}
          npm run test --spec "cypress/e2e/${{ env.spec-file }}.cy.js"
        

